# Generated by Django 5.0.4 on 2024-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_contact', models.CharField(max_length=50)),
                ('stu_city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'db_table': 'Ankit_Table',
            },
        ),
    ]
